// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKHUZIMvQgRVqUhPLt8K3QjhLqY5RF4JY',
    appId: '1:95945129620:web:f2b7535a35d5f6ced53e81',
    messagingSenderId: '95945129620',
    projectId: 'glow-2aa80',
    authDomain: 'glow-2aa80.firebaseapp.com',
    storageBucket: 'glow-2aa80.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7q3A1iZMlglvXu_nILjXy3VchHC0Ttic',
    appId: '1:95945129620:android:9e7c9959537f6552d53e81',
    messagingSenderId: '95945129620',
    projectId: 'glow-2aa80',
    storageBucket: 'glow-2aa80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDym9tPSZhjPGGDxcgWlfzPmmACDWtnMH4',
    appId: '1:95945129620:ios:64bb47e8011db20ed53e81',
    messagingSenderId: '95945129620',
    projectId: 'glow-2aa80',
    storageBucket: 'glow-2aa80.firebasestorage.app',
    iosBundleId: 'com.example.glow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDym9tPSZhjPGGDxcgWlfzPmmACDWtnMH4',
    appId: '1:95945129620:ios:64bb47e8011db20ed53e81',
    messagingSenderId: '95945129620',
    projectId: 'glow-2aa80',
    storageBucket: 'glow-2aa80.firebasestorage.app',
    iosBundleId: 'com.example.glow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKHUZIMvQgRVqUhPLt8K3QjhLqY5RF4JY',
    appId: '1:95945129620:web:7cd65d982f859028d53e81',
    messagingSenderId: '95945129620',
    projectId: 'glow-2aa80',
    authDomain: 'glow-2aa80.firebaseapp.com',
    storageBucket: 'glow-2aa80.firebasestorage.app',
  );
}
